---
engines:

  # https://docs.codeclimate.com/v1.0/docs/duplication
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  # https://docs.codeclimate.com/v1.0/docs/fixme
  fixme:
    enabled: true

ratings:
  paths:
  - "**.rb"

exclude_paths:
- spec/**/*
- ".rubocop.yml"
