---
engines:

  # https://docs.codeclimate.com/v1.0/docs/bundler-audit
  bundler-audit:
    enabled: true

  # https://docs.codeclimate.com/v1.0/docs/duplication
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  # https://docs.codeclimate.com/v1.0/docs/fixme
  fixme:
    enabled: true

ratings:
  paths:
  - Gemfile.lock
  - "**.rb"

exclude_paths:
- spec/
