sudo: false # http://docs.travis-ci.com/user/migrating-from-legacy/

language: ruby
rvm:
  - 2.1.2
  - 2.2.4

cache:
  - bundler

env:
  - DYNAMEISTER_ENV=ci

before_install:
  - mkdir /tmp/dynamodb
  - curl -L http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb
  - gem update bundler
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &

script:
  - bundle exec rspec
