language: ruby

rvm:
  - 2.1.2
  - 2.2.1

cache:
  - bundler

sudo: false

env:
  - DYNAMEISTER_ENV=ci

install:
  - mkdir /tmp/dynamodb
  - wget -O - http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb

before_script:
  - mv /tmp/dynamodb/* /tmp/dynamodb/dynamodb
  - java -Djava.library.path=/tmp/dynamodb/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/dynamodb/DynamoDBLocal.jar -inMemory &

script: bundle exec rspec

