language: ruby

addons:
    code_climate:
        repo_token: 738462170bd3cc68eab974fb156df0840d545ce75b49c0b5675c645940008cff

rvm:
  - 2.1.2
  - 2.2.1

sudo: false

env:
  - DYNAMEISTER_ENV=ci

cache:
  - bundler

before_install:
  - mkdir /tmp/dynamodb
  - curl -L http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest | tar xz --directory /tmp/dynamodb
  - gem update bundler
  - java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -inMemory &

script: bundle exec rspec

